#!/bin/busybox sh
#
rescue_shell() {
    echo "Something went wrong. Dropping to a shell."
    exec sh
}

# Mount the /proc and /sys filesystems.
mount -t devtmpfs none /dev
mount -t proc none /proc
mount -t sysfs none /sys

# Do your stuff here.
echo "This script just mounts and boots the rootfs and maybe fscks it, nothing else! Screw you!"

# Mount the root filesystem.
# 8ba7f391-11cd-45bb-82f0-b65e9bf7533a -> root
mount -o ro $(findfs UUID=8ba7f391-11cd-45bb-82f0-b65e9bf7533a) /mnt/root || rescue_shell

# Clean up.
umount /proc
umount /sys

# Boot the real thing.
exec switch_root /mnt/root /usr/lib/systemd/systemd
